[tool.poetry]
name = "create-pod"
version = "0.1.0"
description = ""
authors = ["lukejagg <lukejagg@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kubernetes = "^31.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
